trigger:
- working

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  displayName: 'Use Node 14.x'
  inputs:
    version: 14.x.x

- script: |
    npm install
    npm run build
  displayName: 'npm install, check and build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      dist/*
      README.md
      CHANGELOG.md
      LICENSE.md
      package.json
    TargetFolder: '$(Build.StagingDirectory)'    
  displayName: 'Copy output'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
